### ISSUE TITLE
Can't select text in IE

### ISSUE THREAD

**Issue by irenadzambo** [mendix/Bootstrap-RTE#22] opened 2017-04-05 14:49 UTC
I can't select the input of the widget when working in IE. Internet Explorer is the main browser used by my client and they need to copy-paste a lot as part of their work process. It would be great if this issue could be fixed.

**Comment by jeroen-huizer-conclusion** [comment] 2017-04-07 08:26
This is caused by the clear formatting toolbar button, the associated command (html) is not supported by IE (or any other).
I submitted a pull request that fixes this issue by replacing it with the removeFormat command.

**Comment by JelteMX** [comment] 2017-04-07 11:08
added PR #20 to release [3.3.0](https://github.com/mendix/Bootstrap-RTE/releases/tag/v3.3.0). That should fix the problem

**Comment by JelteMX** [comment] 2018-03-26 11:09
Should be fixed in [latest version](https://github.com/mendix/Bootstrap-RTE/releases/tag/v4.0.0)

**Closed by JelteMX** 2018-03-26 11:09 UTC
